aero-model-lib.url=https://github.com/lucasrgt/aero-model-lib.git
aero-model-lib.revision=143921a64194507dd81728169d301ca6de04c097
aero-machine-api.url=https://github.com/lucasrgt/aero-machine-api.git
aero-machine-api.revision=b1776855e7499e439c90ee8e6b1d4ac2b6bc28ef
aero-devtools.url=https://github.com/lucasrgt/betamc-modding-aero-devtools.git
aero-devtools.revision=ee1e2eb4504dde78be26a02e84338e6023595813
betavault.url=https://github.com/lucasrgt/betavault.git
betavault.revision=22d28a06f1baf431365f0951f8a352d8995d734b
betavault.version=1.0.0
